version: '3.8'

services:

# Nginx
  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - mysql

# PHP
  php:
    image: php:8.1-fpm
    container_name: laravel_app
    volumes:
      - ./php:/var/www/html
  
# Redis Service (Optional)
  redis:
    image: redis:latest
    container_name: laravel_redis
    networks:
      - laravel
  
# Mailhog Service (Optional)
  mailhog:
    image: mailhog/mailhog
    container_name: laravel_mailhog
    ports:
      - "8025:8025"
    networks:
      - laravel

# MySQL
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
